# -*- coding: utf-8 -*-
"""ScriptMaestro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NH9mOQ9VhVuSHSwwKjPQfjrNoOzRtMNV
"""

import pandas as pd
import ast
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("✅ ¡Librerías importadas!")

print("Cargando los 3 archivos CSV originales...")
try:
    df_meta = pd.read_csv('movies_metadata.csv', low_memory=False)
    df_credits = pd.read_csv('credits.csv')
    df_keywords = pd.read_csv('keywords.csv')
    print("Archivos cargados.")
except FileNotFoundError:
    print("\n¡ERROR! 🛑 No se encontraron los 3 archivos CSV originales.")
    print("Sube 'movies_metadata.csv', 'credits.csv' y 'keywords.csv' y re-ejecuta.")

# --- Limpieza de IDs (El paso clave antes de unir) ---
print("Limpiando IDs para la fusión...")
df_meta['id'] = pd.to_numeric(df_meta['id'], errors='coerce')
df_meta = df_meta.dropna(subset=['id'])
df_meta['id'] = df_meta['id'].astype(int)

df_keywords['id'] = df_keywords['id'].astype(int)
df_credits['id'] = df_credits['id'].astype(int)

# --- Fusión (Merge) ---
print("Fusionando los 3 archivos...")
df = df_meta.merge(df_keywords, on='id', how='left')
df = df.merge(df_credits, on='id', how='left')

# (Opcional) Eliminar duplicados de 'id' que pudieron surgir
df = df.drop_duplicates(subset='id').reset_index(drop=True)

print(f"✅ ¡Fusión completada! Forma original del DataFrame: {df.shape}")

print(f"Reduciendo el DataFrame a las 10,000 películas más populares...")

# 1. Asegurarnos que 'popularity' sea un número
# 'coerce' convierte los valores malos en NaT/NaN
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')

# 2. Eliminar filas donde la popularidad sea NaN (si las hay)
df = df.dropna(subset=['popularity'])

# 3. Ordenar por popularidad (de mayor a menor) y tomar las 10,000 primeras
df = df.sort_values('popularity', ascending=False).head(10000)

# 4. Importante: Resetear el índice
# Esto es vital para que el mapeo (indices) funcione después
df = df.reset_index(drop=True)

print(f"✅ ¡Dataset reducido! Nueva forma: {df.shape}")

print("Definiendo funciones de 'parsing' (limpieza)...")

def safe_literal_eval(s):
    try:
        return ast.literal_eval(s)
    except (ValueError, SyntaxError, TypeError):
        return []

def get_names(data_list_str):
    data_list = safe_literal_eval(data_list_str)
    if isinstance(data_list, list):
        names = [item['name'].lower().replace(" ", "") for item in data_list if 'name' in item]
        return names
    return []

def get_top_cast(cast_list_str, top_n=3):
    cast_list = safe_literal_eval(cast_list_str)
    if isinstance(cast_list, list):
        names = [item['name'].lower().replace(" ", "") for item in cast_list[:top_n] if 'name' in item]
        return names
    return []

def get_director(crew_list_str):
    crew_list = safe_literal_eval(crew_list_str)
    if isinstance(crew_list, list):
        for member in crew_list:
            if member.get('job') == 'Director':
                return member.get('name', '').lower().replace(" ", "")
    return ""

print("✅ ¡Funciones 'get_names', 'get_top_cast' y 'get_director' definidas!")

print("Iniciando la creación de la 'metadata_soup'...")

# 4a. Limpieza de NaNs (Paso 1: para parsing)
print("Limpiando NaNs (genres, keywords, cast, crew)...")
df['genres'] = df['genres'].fillna('[]')
df['keywords'] = df['keywords'].fillna('[]')
df['cast'] = df['cast'].fillna('[]')
df['crew'] = df['crew'].fillna('[]')

# 4b. Aplicar las funciones de parsing
print("Aplicando funciones (creando _list)...")
df['genres_list'] = df['genres'].apply(get_names)
df['keywords_list'] = df['keywords'].apply(get_names)
df['cast_list'] = df['cast'].apply(get_top_cast)
df['director'] = df['crew'].apply(get_director)

# 4c. Limpieza de NaNs (Paso 2: Fix del TypeError)
print("Limpiando NaNs (overview, director)...")
df['overview'] = df['overview'].fillna('')
df['director'] = df['director'].fillna('')

# 4d. Definir la función para crear la Sopa
def create_metadata_soup(row):
    genres = ' '.join(row['genres_list'])
    keywords = ' '.join(row['keywords_list'])
    cast = ' '.join(row['cast_list'])

    genres_weighted = (genres + ' ') * 2
    keywords_weighted = (keywords + ' ') * 3
    cast_weighted = (cast + ' ') * 3
    director_weighted = (row['director'] + ' ') * 3

    return (
        row['overview'] + ' ' +
        genres_weighted +
        keywords_weighted +
        cast_weighted +
        director_weighted
    )

# 4e. Aplicar la función para crear la Sopa
print("Aplicando 'create_metadata_soup'... (Esto tardará menos ahora)")
df['metadata_soup'] = df.apply(create_metadata_soup, axis=1)

print("\n✅ ¡'metadata_soup' creada exitosamente!")

print("Iniciando la Vectorización TF-IDF...")

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=10000  # Mantenemos 10k palabras, pero ahora sobre 10k películas
)
tfidf_matrix = tfidf.fit_transform(df['metadata_soup'])

print("\n✅ ¡Vectorización TF-IDF completada!")
print(f"Forma de la Matriz TF-IDF: {tfidf_matrix.shape}")

print("Calculando Similitud Coseno...")

# ¡Esto ahora SÍ funcionará en Colab!
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

print("\n✅ ¡Cálculo de Similitud Coseno completado!")
print(f"Forma de la Matriz de Similitud: {cosine_sim.shape}")

print("Creando la función de recomendación... (¡Versión CORREGIDA!)")

# --- ¡FIX #1: Creación correcta del Mapeo de Título a Índice! ---
# 1. Crear la serie base
s = pd.Series(df.index, index=df['title'])

# 2. Filtrar la serie para ELIMINAR TÍTULOS DUPLICADOS (el '~' significa 'no')
#    Nos quedamos solo con la 'primera' aparición de cada título.
indices = s[~s.index.duplicated(keep='first')]

print("Mapeo de 'índices' (sin duplicados) creado.")

# 2. Definir la función (con el FIX #2)
def get_recommendations(title, cosine_sim_matrix=cosine_sim, num_recommendations=10):

    # Búsqueda simple (esto estaba bien)
    if title not in indices:
        matching_titles = [t for t in indices.index if title.lower() in str(t).lower()]
        if not matching_titles:
            return f"Error: No se encontró '{title}' ni títulos similares en el Top 10k."
        print(f"No se encontró '{title}'. Mostrando resultados para '{matching_titles[0]}'")
        title = matching_titles[0]

    # Obtener el índice (la posición) de la película
    idx = indices[title]

    # --- ¡FIX #2: El "Seguro" para el ValueError! ---
    # Si 'idx' sigue siendo una lista (Serie de Pandas) porque el título
    # aún tiene duplicados (ej. 'Cinderella'), tomamos solo el PRIMERO.
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]
    # --- Fin del Fix ---

    # Obtener los puntajes de similitud (esta línea ahora es segura)
    sim_scores = list(enumerate(cosine_sim_matrix[idx]))

    # Ordenar las películas por similitud
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Obtener las N más similares
    top_sim_scores = sim_scores[1 : num_recommendations + 1]

    # Obtener los índices de esas películas
    movie_indices = [i[0] for i in top_sim_scores]

    # Devolver los títulos
    return df['title'].iloc[movie_indices]

print("✅ ¡Función 'get_recommendations' (corregida) definida!")

print("--- [VALIDACIÓN CUALITATIVA] ---")

movie_title_1 = 'The Dark Knight'
print(f"\nRecomendaciones para: '{movie_title_1}'")
print("------------------------------------------")
print(get_recommendations(movie_title_1))

movie_title_2 = 'Inception'
print(f"\nRecomendaciones para: '{movie_title_2}'")
print("------------------------------------------")
print(get_recommendations(movie_title_2))

movie_title_3 = 'Pulp Fiction'
print(f"\nRecomendaciones para: '{movie_title_3}'")
print("------------------------------------------")
print(get_recommendations(movie_title_3, num_recommendations=5))

# Esta es la que probablemente dio el error. ¡Ahora debería funcionar!
movie_title_4 = 'A Nightmare on Elm Street'
print(f"\nRecomendaciones para: '{movie_title_4}'")
print("------------------------------------------")
print(get_recommendations(movie_title_4, num_recommendations=5))

print("\n--- [FIN] ¡Sistema de recomendación (Top 10k) completo! ---")

#################################################################
# SCRIPT MAESTRO ÚNICO: SISTEMA DE RECOMENDACIÓN (COMPLETO)
#
# Este script ejecuta todo el proceso:
# 1. Carga y Fusión de los 3 CSV originales.
# 2. Solución de RAM: Reduce el dataset al Top 10k más popular.
# 3. Definición de Funciones de Limpieza (Parsing).
# 4. Creación de la 'Metadata Soup' (con fixes de TypeError).
# 5. Generación de Gráficos del EDA.
# 6. Construcción del Modelo (TF-IDF y Similitud Coseno).
# 7. Creación de la Función de Recomendación (con fixes de ValueError).
# 8. Validación final del modelo.
# 9.
#10.  VALIDACIÓN CIENTÍFICA (Matriz de Coherencia).
# 11.  DESPLIEGUE (Generación de archivos .pkl para AWS).
#################################################################

print("--- [INICIO] INICIANDO PROCESO COMPLETO ---")

# --- 1. IMPORTAR LIBRERÍAS (TODAS JUNTAS) ---
print("\n[Paso 1/9] Importando librerías...")
import pandas as pd
import ast
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import sys
print("   > ¡Librerías importadas!")

# --- 2. CARGAR Y FUSIONAR (MERGE) LOS 3 ARCHIVOS ORIGINALES ---
print("\n[Paso 2/9] Cargando y fusionando (merge) los 3 archivos CSV...")
try:
    df_meta = pd.read_csv('movies_metadata.csv', low_memory=False)
    df_credits = pd.read_csv('credits.csv')
    df_keywords = pd.read_csv('keywords.csv')
    print("   > 3 archivos CSV cargados en memoria.")
except FileNotFoundError:
    print("\n¡ERROR! 🛑 No se encontraron los 3 archivos CSV originales.")
    print("Asegúrate de tener 'movies_metadata.csv', 'credits.csv' y 'keywords.csv' en la misma carpeta.")
    # sys.exit() # Detendría el script

# Limpieza de IDs (El paso clave antes de unir)
print("   > Limpiando IDs para la fusión...")
df_meta['id'] = pd.to_numeric(df_meta['id'], errors='coerce')
df_meta = df_meta.dropna(subset=['id'])
df_meta['id'] = df_meta['id'].astype(int)

df_keywords['id'] = df_keywords['id'].astype(int)
df_credits['id'] = df_credits['id'].astype(int)

# Fusión (Merge)
print("   > Fusionando DataFrames...")
df = df_meta.merge(df_keywords, on='id', how='left')
df = df.merge(df_credits, on='id', how='left')

# Eliminar duplicados de 'id' que pudieron surgir
df = df.drop_duplicates(subset='id').reset_index(drop=True)
print(f"   > ¡Fusión completada! Forma original: {df.shape}")

# --- 3. ¡FIX DE RAM! REDUCIR EL DATASET AL TOP 10K ---
print("\n[Paso 3/9] Solución de RAM: Reduciendo el DataFrame al Top 10k...")

# 1. Asegurarnos que 'popularity' sea un número
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
df = df.dropna(subset=['popularity'])

# 2. Ordenar por popularidad y tomar las 10,000 mejores
df = df.sort_values('popularity', ascending=False).head(10000)

# 3. Importante: Resetear el índice (Clave para el Paso 7)
df = df.reset_index(drop=True)
print(f"   > ¡Dataset reducido! Nueva forma: {df.shape}")

# --- 4. DEFINIR FUNCIONES DE LIMPIEZA (PARSING) ---
print("\n[Paso 4/9] Definiendo funciones de 'parsing'...")

def safe_literal_eval(s):
    try:
        return ast.literal_eval(s)
    except (ValueError, SyntaxError, TypeError):
        return []

def get_names(data_list_str):
    data_list = safe_literal_eval(data_list_str)
    if isinstance(data_list, list):
        names = [item['name'].lower().replace(" ", "") for item in data_list if 'name' in item]
        return names
    return []

def get_top_cast(cast_list_str, top_n=3):
    cast_list = safe_literal_eval(cast_list_str)
    if isinstance(cast_list, list):
        names = [item['name'].lower().replace(" ", "") for item in cast_list[:top_n] if 'name' in item]
        return names
    return []

def get_director(crew_list_str):
    crew_list = safe_literal_eval(crew_list_str)
    if isinstance(crew_list, list):
        for member in crew_list:
            if member.get('job') == 'Director':
                return member.get('name', '').lower().replace(" ", "")
    return ""
print("   > Funciones de limpieza definidas.")

# --- 5. CREAR LA 'METADATA SOUP' (CON FIXES DE TYPEERROR) ---
print("\n[Paso 5/9] Creando 'metadata_soup' (Limpieza y Ponderación)...")

# 5a. Limpieza de NaNs (para parsing)
df['genres'] = df['genres'].fillna('[]')
df['keywords'] = df['keywords'].fillna('[]')
df['cast'] = df['cast'].fillna('[]')
df['crew'] = df['crew'].fillna('[]')

# 5b. Aplicar las funciones de parsing
print("   > Aplicando 'get_names', 'get_top_cast', 'get_director'...")
df['genres_list'] = df['genres'].apply(get_names)
df['keywords_list'] = df['keywords'].apply(get_names)
df['cast_list'] = df['cast'].apply(get_top_cast)
df['director'] = df['crew'].apply(get_director)

# 5c. ¡FIX DE TYPEERROR! (float + str)
print("   > Aplicando fix de TypeError (limpiando 'overview' y 'director')...")
df['overview'] = df['overview'].fillna('')
df['director'] = df['director'].fillna('')

# 5d. Definir la función para crear la Sopa
def create_metadata_soup(row):
    genres = ' '.join(row['genres_list'])
    keywords = ' '.join(row['keywords_list'])
    cast = ' '.join(row['cast_list'])

    genres_weighted = (genres + ' ') * 2
    keywords_weighted = (keywords + ' ') * 3
    cast_weighted = (cast + ' ') * 3
    director_weighted = (row['director'] + ' ') * 3

    return (
        row['overview'] + ' ' +
        genres_weighted +
        keywords_weighted +
        cast_weighted +
        director_weighted
    )

# 5e. Aplicar la creación de la Sopa
print("   > Creando la 'sopa' final... (Esto tardará menos ahora)")
df['metadata_soup'] = df.apply(create_metadata_soup, axis=1)
print("   > ¡'metadata_soup' creada!")

# --- 6. ANÁLISIS EXPLORATORIO DE DATOS (EDA) ---
print("\n[Paso 6/9] Generando gráficos del Análisis Exploratorio (EDA)...")
sns.set(style="whitegrid")

# Gráfico 1: Tipo de Contenido
try:
    print("   > Generando Gráfico 1: Tipo de Contenido...")
    valid_types = ['Movie', 'TV Show']
    df_filtered_types = df[df['type'].isin(valid_types)]
    type_counts = df_filtered_types['type'].value_counts()
    plt.figure(figsize=(10, 6))
    sns.countplot(x='type', data=df_filtered_types, order=type_counts.index, palette="viridis")
    plt.title('Proporción de Películas vs. Series de TV (Top 10k Populares)', fontsize=16)
    plt.savefig('grafico_1_tipo_contenido.png')
    plt.close()
    print("   > Gráfico 1 guardado.")
except KeyError:
    print("   > ADVERTENCIA: Columna 'type' no encontrada. Omitiendo Gráfico 1.")

# Gráfico 2: Años de Estreno
print("   > Generando Gráfico 2: Años de Estreno...")
release_dates = pd.to_datetime(df['release_date'], errors='coerce')
release_years = release_dates.dt.year.dropna()
release_years = release_years[(release_years > 1900) & (release_years <= 2025)]
plt.figure(figsize=(14, 7))
sns.histplot(release_years, bins=60, kde=False, color="blue")
plt.title('Distribución de Años de Estreno (Top 10k Populares)', fontsize=16)
plt.savefig('grafico_2_anios_estreno.png')
plt.close()
print("   > Gráfico 2 guardado.")

# Gráfico 3: Top 15 Géneros
print("   > Generando Gráfico 3: Top 15 Géneros...")
genres_exploded = df.explode('genres_list')
top_genres = genres_exploded[genres_exploded['genres_list'] != '']['genres_list'].value_counts().head(15)
plt.figure(figsize=(14, 8))
sns.barplot(x=top_genres.values, y=top_genres.index, palette='mako')
plt.title('Top 15 Géneros Más Comunes (Top 10k Populares)', fontsize=16)
plt.savefig('grafico_3_top_generos.png')
plt.close()
print("   > Gráfico 3 guardado.")

# Gráfico 4: Distribución de Calificaciones
print("   > Generando Gráfico 4: Distribución de Calificaciones...")
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')
votos_reales = df[df['vote_average'] > 0]['vote_average']
plt.figure(figsize=(12, 7))
sns.histplot(votos_reales, bins=40, kde=True, color="purple")
plt.title('Distribución de Calificaciones Promedio (Top 10k Populares)', fontsize=16)
mean_val = votos_reales.mean()
plt.axvline(mean_val, color='red', linestyle='--', label=f'Promedio: {mean_val:.2f}')
plt.legend()
plt.savefig('grafico_4_distribucion_votos.png')
plt.close()
print("   > Gráfico 4 guardado.")

# Gráfico 5: Matriz de Correlación
print("   > Generando Gráfico 5: Matriz de Correlación...")
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')
df['runtime'] = pd.to_numeric(df['runtime'], errors='coerce')
df['vote_count'] = pd.to_numeric(df['vote_count'], errors='coerce')
df_numeric = df[
    (df['budget'] > 1000) & (df['revenue'] > 1000) & (df['vote_count'] > 100)
][['budget', 'revenue', 'popularity', 'runtime', 'vote_average', 'vote_count']]
corr_matrix = df_numeric.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', linewidths=.5)
plt.title('Matriz de Correlación (Top 10k Populares)', fontsize=16)
plt.savefig('grafico_5_correlacion.png')
plt.close()
print("   > Gráfico 5 guardado.")
print("   > ¡EDA Completo!")

# --- 7. CONSTRUCCIÓN DEL MODELO (TF-IDF) ---
print("\n[Paso 7/9] Construyendo el modelo (TF-IDF)...")
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=10000  # Usar 10k palabras en nuestro dataset de 10k películas
)
tfidf_matrix = tfidf.fit_transform(df['metadata_soup'])
print(f"   > Matriz TF-IDF creada. Forma: {tfidf_matrix.shape}")

# --- 8. CONSTRUCCIÓN DEL MODELO (SIMILITUD COSENO) ---
print("\n[Paso 8/9] Construyendo el modelo (Similitud Coseno)...")
# ¡Esto ahora SÍ funcionará en Colab!
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(f"   > Matriz de Similitud creada. Forma: {cosine_sim.shape}")

# --- 9. FUNCIÓN DE RECOMENDACIÓN Y VALIDACIÓN (CON FIX DE VALUEERROR) ---
print("\n[Paso 9/9] Creando función de recomendación y validando...")

# ¡FIX DE VALUEERROR! (Creación correcta de 'indices')
s = pd.Series(df.index, index=df['title'])
indices = s[~s.index.duplicated(keep='first')] # Elimina títulos duplicados
print("   > Mapeo de 'índices' (sin duplicados) creado.")

def get_recommendations(title, cosine_sim_matrix=cosine_sim, num_recommendations=10):
    if title not in indices:
        matching_titles = [t for t in indices.index if title.lower() in str(t).lower()]
        if not matching_titles:
            return f"Error: No se encontró '{title}' ni títulos similares en el Top 10k."
        print(f"   > No se encontró '{title}'. Mostrando resultados para '{matching_titles[0]}'")
        title = matching_titles[0]

    idx = indices[title]

    # ¡FIX DE VALUEERROR! (El "seguro" por si acaso)
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    sim_scores = list(enumerate(cosine_sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    top_sim_scores = sim_scores[1 : num_recommendations + 1]
    movie_indices = [i[0] for i in top_sim_scores]
    return df['title'].iloc[movie_indices]

print("   > ¡Función 'get_recommendations' (corregida) definida!")

# --- ¡VALIDACIÓN FINAL! ---
print("\n--- [VALIDACIÓN CUALITATIVA DEL MODELO TOP 10K] ---")

movie_title_1 = 'The Dark Knight'
print(f"\nRecomendaciones para: '{movie_title_1}'")
print("------------------------------------------")
print(get_recommendations(movie_title_1))

movie_title_2 = 'Inception'
print(f"\nRecomendaciones para: '{movie_title_2}'")
print("------------------------------------------")
print(get_recommendations(movie_title_2))

movie_title_3 = 'Pulp Fiction'
print(f"\nRecomendaciones para: '{movie_title_3}'")
print("------------------------------------------")
print(get_recommendations(movie_title_3, num_recommendations=5))

movie_title_4 = 'A Nightmare on Elm Street'
print(f"\nRecomendaciones para: '{movie_title_4}'")
print("------------------------------------------")
print(get_recommendations(movie_title_4, num_recommendations=5))


# --- 10. GENERACIÓN DE LA MATRIZ DE COHERENCIA (VALIDACIÓN VISUAL) ---
print("\n[Paso 10/9] Generando Matriz de Coherencia de Géneros...")

# Definimos películas representativas de géneros puros
test_movies_dict = {
    'Animation': 'Toy Story',
    'Horror': 'Scream',
    'Action': 'The Dark Knight',
    'Romance': 'Titanic',
    'Science Fiction': 'The Matrix' # Nota: En tu dataset puede estar como 'Science Fiction' o 'Sci-Fi'
}

# Preparamos la matriz
matrix_labels = list(test_movies_dict.keys())
coherence_matrix = pd.DataFrame(0, index=matrix_labels, columns=matrix_labels)

# Llenamos la matriz
for target_genre, title in test_movies_dict.items():
    # Obtenemos 10 recomendaciones
    # Nota: Usamos try/except por si el título exacto no está en el Top 10k
    try:
        recs = get_recommendations(title, num_recommendations=10)

        # Si recs es string (mensaje de error), saltamos
        if isinstance(recs, str):
            continue

        for rec_title in recs:
            # Buscamos el género principal de la recomendación en el DF original
            rec_genres = df[df['title'] == rec_title]['genres_list'].iloc[0]

            # Verificamos si alguno de sus géneros coincide con nuestras columnas
            for g in rec_genres: # rec_genres ya es una lista gracias a tu paso 4
                # Mapeo manual rápido por si hay variaciones (Sci-Fi vs Science Fiction)
                if g.lower() == 'sci-fi': g = 'Science Fiction'

                # Capitalizamos para coincidir con las columnas
                g_cap = g.title()
                if g == 'sciencefiction': g_cap = 'Science Fiction' # Tu limpieza quitó espacios

                # Buscamos coincidencia aproximada
                for label in matrix_labels:
                    if label.lower().replace(" ", "") in g.lower():
                        coherence_matrix.loc[target_genre, label] += 1
                        break # Contamos solo el género principal coincidente
    except Exception as e:
        print(f"Salto en {title}: {e}")

# Graficamos
plt.figure(figsize=(10, 8))
sns.heatmap(coherence_matrix, annot=True, cmap='Blues', fmt='g', linewidths=.5)
plt.title('Matriz de Coherencia: ¿El modelo respeta los géneros?', fontsize=15)
plt.xlabel('Género Recomendado', fontsize=12)
plt.ylabel('Género de Entrada (Input)', fontsize=12)
plt.savefig('grafico_6_matriz_coherencia.png') # ¡Guardamos la imagen!
plt.close()
print("   > Gráfico 6 (Matriz de Coherencia) guardado.")



# --- 11. EXPORTAR MODELO PARA AWS (SERIALIZACIÓN) ---
print("\n[Paso 11/9] Guardando archivos para despliegue en Nube...")
import joblib

# Guardamos la matriz de similitud (El "cerebro" del modelo)
joblib.dump(cosine_sim, 'cosine_sim_model.pkl')

# Guardamos el dataframe reducido (Necesario para traducir índice -> título)
df[['title', 'genres_list']].to_pickle('movie_data.pkl')

# Guardamos los índices
pd.Series(df.index, index=df['title']).drop_duplicates().to_pickle('indices.pkl')

print("   > Archivos .pkl generados exitosamente (listos para subir a S3/EC2).")


print("\n--- [FIN] ¡Sistema de recomendación completo! ---")